NUMPY LIBRARIE

In [2]:
#numpy is python lib
#numpy is stands for numerical python
#numpy is used for working with array

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(np.__version__)


1.26.4


0-D Array

In [5]:
import numpy as np
arr1=np.array(24)
print(arr1)

24


1-D Array

In [6]:
import numpy as np
arr2=np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


2-D Array

In [7]:
import numpy as np
arr3=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr3)

[[1 2 3 4 5]
 [5 6 7 8 9]]


3-D Array

In [8]:
import numpy as np
arr4=np.array([[[1,2,3],[1,3,4],[7,8,9]]])
print(arr4)

[[[1 2 3]
  [1 3 4]
  [7 8 9]]]


Check number of dimenssions

In [11]:
print(arr4.ndim)
print(arr3.ndim)

3
2


Access array element

In [14]:
a=np.array([1,2,3,4])
print(a[2])

3


In [17]:
a=np.array([2,3,4,5,6,7])
print(a[2]+a[4])

10


In [ ]:
import numpy as np
arr3=np.array([[1,2,3,4,5,9,8],[5,6,7,8,9,8,9]])
print('sec elementy on first row',arr3[0,1])

sec elementy on first row 2


In [21]:
print('fifth element on sec row',arr3[1,4])

fifth element on sec row 9


In [22]:
x=np.array([[[1,2,3],[3,4,5]],[[3,4,5],[8,9,8]]])
print(arr[0,1,2])

4


Neagative indexing

In [23]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,8]])
print('last element from 2nd dim:',arr[1,-1])

last element from 2nd dim: 8


In [ ]:
x=np.array([1,5,4,3,2])
print(x[ :4])


[1 5 4 3]
[]


In [29]:
print(x[-1:-5])

[]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]
